"""Initial migration

Revision ID: 025f29185b1f
Revises: 
Create Date: 2023-07-27 11:54:50.107738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "025f29185b1f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
